### PR TITLE
create overview page

### PR DESCRIPTION
**Pull request by ErinBecker**
Creates workshop home page for social sciences lessons.

### CODE REVIEW

**Comment by ErinBecker** [comment]
@tracykteal - could you please review and merge. I'd like to include this link in the community interest form for the social sciences call. 

Minor issue is that I couldn't remember how to keep the schedule from showing up on the homepage. If you know how to do this, please let me know or put in a PR.

**Comment by tracykteal** [comment]
Line 8 has a ... Do you want to merge though, while that's in progress, so you can sequentially add, but get something up now?

**Comment by tracykteal** [comment]
Looks good. There is a ... that could be updated after merge.

**Comment by ErinBecker** [comment]
Thanks @tracykteal. I'll get that updated and put in a new PR.

**Pull request merged**
